name: 'MVN build'
description: 'mvnbuild'
inputs:
  repo:
    description: 'Which repo'
    required: true
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
        with:
          repository: FoxBukkit/${{ inputs.repo }}
          path: ${{ inputs.repo }}
      - name: Build with Maven
        shell: bash
        run: mvn --batch-mode --update-snapshots clean package deploy -s "$GITHUB_WORKSPACE/settings.xml"
        working-directory: ${{ inputs.repo }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
