name: Build packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # strategy:
    #   matrix:
    #     package:
    #     - accounts-client
    #     - config-dependency
    #     - threading-dependency
    #     - redis-dependency
    #     - plexus-compiler-luaj
    #     - collectivization-maven-plugin
    #     - foxbukkit-permissions
    #     - foxbukkit-chat
    #     - foxbukkit-lua
    steps:
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          server-id: foxbukkit-repo
          settings-path: ${{ github.workspace }}
      - uses: ./actions/mvnbuild.yml
        with:
          repo: accounts-client
