name: Build packages
on: [push]
jobs:
  maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # - name: config-dependency
      #   uses: ./.github/actions/mvnbuild
      #   with:
      #     repo: config-dependency
      #     token: ${{ github.token }}
      # - name: plexus-compiler-luaj
      #   uses: ./.github/actions/mvnbuild
      #   with:
      #     repo: plexus-compiler-luaj
      #     token: ${{ github.token }}
      # - name: foxbukkit-permissions
      #   uses: ./.github/actions/mvnbuild
      #   with:
      #     repo: foxbukkit-permissions
      #     token: ${{ github.token }}
      # - name: foxbukkit-chat
      #   uses: ./.github/actions/mvnbuild
      #   with:
      #     repo: foxbukkit-chat
      #     token: ${{ github.token }}
      # - name: foxbukkit-lua
      #   uses: ./.github/actions/mvnbuild
      #   with:
      #     repo: foxbukkit-lua
      #     token: ${{ github.token }}
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: docker
          build-args: |
            GIT_REVISION=${{ github.sha }}
          tags: |
            ghcr.io/foxbukkit/packages/server:latest
