name: Build Docker image
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download previous image
        run: docker pull ghcr.io/foxbukkit/packages/server:latest
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: docker
          build-args: |
            GIT_REVISION=${{ github.sha }}
          tags: |
            ghcr.io/foxbukkit/packages/server:latest
